// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIXpQHT0SaMTa9ps30N7uq9244MqozhHw',
    appId: '1:822118738130:web:659399ba5defb4b80f650b',
    messagingSenderId: '822118738130',
    projectId: 'blood-donor-919',
    authDomain: 'blood-donor-919.firebaseapp.com',
    storageBucket: 'blood-donor-919.firebasestorage.app',
    measurementId: 'G-156920WWFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoPdmCyEM-J7R6YnAsjvdkxADetTrL0JQ',
    appId: '1:822118738130:android:9b2bdcb30bf149f20f650b',
    messagingSenderId: '822118738130',
    projectId: 'blood-donor-919',
    storageBucket: 'blood-donor-919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEbKgSI4kPABVDyZufPqo-ydr5OpPRpc',
    appId: '1:822118738130:ios:3fcc1d4e3df8a88b0f650b',
    messagingSenderId: '822118738130',
    projectId: 'blood-donor-919',
    storageBucket: 'blood-donor-919.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEbKgSI4kPABVDyZufPqo-ydr5OpPRpc',
    appId: '1:822118738130:ios:3fcc1d4e3df8a88b0f650b',
    messagingSenderId: '822118738130',
    projectId: 'blood-donor-919',
    storageBucket: 'blood-donor-919.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIXpQHT0SaMTa9ps30N7uq9244MqozhHw',
    appId: '1:822118738130:web:100b85bab994f28f0f650b',
    messagingSenderId: '822118738130',
    projectId: 'blood-donor-919',
    authDomain: 'blood-donor-919.firebaseapp.com',
    storageBucket: 'blood-donor-919.firebasestorage.app',
    measurementId: 'G-L1G1H4MDCE',
  );
}
